version: 2

models:
  - name: orders_stg
    description: "staged table of orders"
    columns:
      - name: order_id
        description: "unique order identifier"
        tests:
          - unique
          - not_null
  - name: order_items_stg
    description: "staged table of order items"
    columns:
      - name: order_item_id
        description: "unique order identifier"
        tests:
          - unique
          - not_null
  - name: products_stg
    description: "staged table of products"
    columns:
      - name: product_id
        description: "unique product identifier"
        tests:
          - unique
          - not_null
  - name: product_prices_stg
    tests:
      - dbt_utils.mutually_exclusive_ranges:
          lower_bound_column: product_price_created_at
          upper_bound_column: product_price_ended_at
          partition_by: product_id
          gaps: not_allowed
    description: "staged table of product prices"
    columns:
      - name: product_price_id
        description: "unique product identifier"
        tests:
          - unique
          - not_null