version: 2

models:
  - name: orders_mart
    description: "curated table of orders"
    columns:
      - name: order_id
        description: "unique order identifier"
        tests:
          - unique
          - not_null